### ISSUE TITLE
[BUG] Assess crashes on simple model with `or_else`.

### ISSUE THREAD

**Issue by derifatives** [genjax-community/genjax#1262]
**Describe the bug**
A simple model (from Jay) that uses `or_else` seems to crash on a call to assess.

**To Reproduce**
```
@genjax.gen
def f():
    flip = jnp.bool_(genjax.flip(p) @ "flip")
    return genjax.normal(0.0, 1.0).or_else(genjax.normal(2.0, 1.0))(flip, (), ()) @ "value"

key = jax.random.PRNGKey(17)
args = ()

f.assess(f.simulate(key, args).get_choices(), args)
```

I expected this to produce a value, but it crashes. Trace:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[62], line 1
----> 1 f.assess(f.simulate(key, args).get_choices(), args)

    [... skipping hidden 1 frame]

File <@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.assess) at 0x7f3e7a548cc0>:52, in assess(__beartype_object_94084111390432, __beartype_get_violation, __beartype_conf, __beartype_object_139906316948352, __beartype_func, *args, **kwargs)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py:613](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py#line=612), in StaticGenerativeFunction.assess(self, sample, args)
    603 @GenerativeFunction.gfi_boundary
    604 @typecheck
    605 def assess(
   (...)
    608     args: Tuple,
    609 ) -> Tuple[ArrayLike, Any]:
    610     syntax_sugar_handled = push_trace_overload_stack(
    611         handler_trace_with_static, self.source
    612     )
--> 613     (retval, score) = assess_transform(syntax_sugar_handled)(sample, args)
    614     return (score, retval)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py:448](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py#line=447), in assess_transform.<locals>.wrapper(constraints, args)
    445 @functools.wraps(source_fn)
    446 def wrapper(constraints, args):
    447     stateful_handler = AssessHandler(constraints)
--> 448     retval = forward(source_fn)(stateful_handler, *args)
    449     (score,) = stateful_handler.yield_state()
    450     return (retval, score)

File <@beartype(genjax._src.core.interpreters.forward.forward.wrapped) at 0x7f3dcce34040>:32, in wrapped(__beartype_object_94084111270288, __beartype_get_violation, __beartype_conf, __beartype_func, *args, **kwargs)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/core/interpreters/forward.py:257](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/core/interpreters/forward.py#line=256), in forward.<locals>.wrapped(stateful_handler, *args)
    253 @functools.wraps(f)
    254 @typecheck
    255 def wrapped(stateful_handler: StatefulHandler, *args):
    256     interpreter = ForwardInterpreter()
--> 257     return interpreter.run_interpreter(
    258         stateful_handler,
    259         f,
    260         *args,
    261     )

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/core/interpreters/forward.py:242](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/core/interpreters/forward.py#line=241), in ForwardInterpreter.run_interpreter(self, stateful_handler, fn, *args, **kwargs)
    240 _closed_jaxpr, (flat_args, _, out_tree) = stage(_inner)(*args)
    241 _jaxpr, consts = _closed_jaxpr.jaxpr, _closed_jaxpr.literals
--> 242 flat_out = self._eval_jaxpr_forward(
    243     stateful_handler,
    244     _jaxpr,
    245     consts,
    246     flat_args,
    247 )
    248 return jtu.tree_unflatten(out_tree(), flat_out)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/core/interpreters/forward.py:227](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/core/interpreters/forward.py#line=226), in ForwardInterpreter._eval_jaxpr_forward(self, stateful_handler, _jaxpr, consts, args)
    225 args = subfuns + invals
    226 if stateful_handler.handles(eqn.primitive):
--> 227     outvals = stateful_handler.dispatch(eqn.primitive, *args, **params)
    228 else:
    229     outvals = eqn.primitive.bind(*args, **params)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py:225](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py#line=224), in StaticHandler.dispatch(self, primitive, *tracers, **_params)
    223 addr = Pytree.tree_unwrap_const(addr)
    224 if primitive == trace_p:
--> 225     v = self.handle_trace(addr, gen_fn, args)
    226     return self.handle_retval(v)
    227 else:

File <@beartype(genjax._src.generative_functions.static.AssessHandler.handle_trace) at 0x7f3e7a537c40>:89, in handle_trace(__beartype_getrandbits, __beartype_get_violation, __beartype_conf, __beartype_object_94084111349072, __beartype_func, *args, **kwargs)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py:439](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/static.py#line=438), in AssessHandler.handle_trace(self, addr, gen_fn, args)
    431 @typecheck
    432 def handle_trace(
    433     self,
   (...)
    436     args: Tuple,
    437 ):
    438     submap = self.get_subsample(addr)
--> 439     (score, v) = gen_fn.assess(submap, args)
    440     self.score += score
    441     return v

File <@beartype(genjax._src.generative_functions.combinators.dimap.DimapCombinator.assess) at 0x7f3e93367240>:52, in assess(__beartype_object_94084111328080, __beartype_get_violation, __beartype_conf, __beartype_object_94084109225568, __beartype_func, *args, **kwargs)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/dimap.py:201](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/dimap.py#line=200), in DimapCombinator.assess(self, sample, args)
    194 @typecheck
    195 def assess(
    196     self,
    197     sample: Sample,
    198     args: tuple,
    199 ) -> tuple[Score, S]:
    200     inner_args = self.argument_mapping(*args)
--> 201     w, inner_retval = self.inner.assess(sample, inner_args)
    202     retval = self.retval_mapping(inner_args, inner_retval)
    203     return w, retval

File <@beartype(genjax._src.generative_functions.combinators.switch.SwitchCombinator.assess) at 0x7f3e9337fb00>:52, in assess(__beartype_object_94084111328080, __beartype_get_violation, __beartype_conf, __beartype_object_94084109225568, __beartype_func, *args, **kwargs)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/switch.py:673](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/switch.py#line=672), in SwitchCombinator.assess(self, sample, args)
    669     return lambda sample, args: self._assess(static_idx, sample, args)
    671 branch_functions = list(map(_inner, range(len(self.branches))))
--> 673 retval_leaves, score = jax.lax.switch(
    674     idx, branch_functions, sample, branch_args
    675 )
    676 (_, retval_defs) = self._empty_assess_defs(sample, args)
    677 retvals = list(
    678     map(
    679         lambda x: jtu.tree_unflatten(retval_defs[x], retval_leaves[x]),
    680         range(len(retval_leaves)),
    681     )
    682 )

    [... skipping hidden 9 frame]

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/switch.py:669](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/switch.py#line=668), in SwitchCombinator.assess.<locals>._inner.<locals>.<lambda>(sample, args)
    668 def _inner(static_idx: int):
--> 669     return lambda sample, args: self._assess(static_idx, sample, args)

File [/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/switch.py:654](http://localhost:8080/opt/conda/envs/genjax/lib/python3.11/site-packages/genjax/_src/generative_functions/combinators/switch.py#line=653), in SwitchCombinator._assess(self, static_idx, sample, args)
    652 def _assess(self, static_idx, sample, args):
    653     branch_gen_fn = self.branches[static_idx]
--> 654     score, retval = branch_gen_fn.assess(sample, args)
    655     (retval_leaves, _) = self._empty_assess_defs(sample, args)
    656     retval_leaves[static_idx] = jtu.tree_leaves(retval)

    [... skipping hidden 1 frame]

File <@beartype(genjax._src.core.generative.core.GenerativeFunctionClosure.assess) at 0x7f3e933284a0>:49, in assess(__beartype_object_94084111328080, __beartype_get_violation, __beartype_conf, __beartype_object_94084109225568, __beartype_func, *args, **kwargs)

TypeError: Method genjax._src.core.generative.core.GenerativeFunctionClosure.assess() parameter args=[(), ()] violates type hint <class 'tuple'>, as list [(), ()] not instance of tuple.



 - Python version: 3.11
 - GenJAX version: 0.5.1

**Additional context**
Add any other context about the problem here.
```

**Comment by sritchie** [comment]
Test comment

**Comment by sritchie** [comment]
First part of the bug, switch.py, line 663:

```
        idx, branch_args = args[0], args[1:]
```

that uncovers a new gem:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.assess) at 0x2940e60c0>", line 52, in assess
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static.py", line 611, in assess
    (retval, score) = assess_transform(syntax_sugar_handled)(sample, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static.py", line 446, in wrapper
    retval = forward(source_fn)(stateful_handler, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.interpreters.forward.forward.wrapped) at 0x2b19b65c0>", line 32, in wrapped
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 253, in wrapped
    return interpreter.run_interpreter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 238, in run_interpreter
    flat_out = self._eval_jaxpr_forward(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 223, in _eval_jaxpr_forward
    outvals = stateful_handler.dispatch(eqn.primitive, *args, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static.py", line 223, in dispatch
    v = self.handle_trace(addr, gen_fn, args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.AssessHandler.handle_trace) at 0x2940e51c0>", line 89, in handle_trace
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static.py", line 437, in handle_trace
    (score, v) = gen_fn.assess(submap, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.combinators.dimap.DimapCombinator.assess) at 0x16c4c93a0>", line 52, in assess
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/combinators/dimap.py", line 201, in assess
    w, inner_retval = self.inner.assess(sample, inner_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.combinators.switch.SwitchCombinator.assess) at 0x16c4dde40>", line 52, in assess
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/combinators/switch.py", line 674, in assess
    (_, retval_defs) = self._empty_assess_defs(sample, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/combinators/switch.py", line 641, in _empty_assess_defs
    _, retval_shape = get_data_shape(branch_gen_fn.assess)(sample, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/staging.py", line 137, in wrapped
    _, data_shape = make_jaxpr(callable, return_shape=True)(*args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.generative.core.GenerativeFunctionClosure.assess) at 0x16c47ac00>", line 52, in assess
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/generative/core.py", line 1726, in assess
    return self.gen_fn.assess(sample, full_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.ExactDensity.assess) at 0x16c528fe0>", line 51, in assess
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/distributions/distribution.py", line 559, in assess
    w = self.estimate_logpdf(key, value, *args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/distributions/distribution.py", line 533, in estimate_logpdf
    w = self.logpdf(v, *args)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/distributions/distribution.py", line 575, in logpdf
    return self.logpdf_evaluator(v, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/pytree.py", line 495, in __call__
    return self.fn(*self.dyn_args, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/distributions/tensorflow_probability/__init__.py", line 30, in logpdf
    d = dist(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 342, in wrapped_init
    default_init(self_, *args, **kwargs)
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/tensorflow_probability/substrates/jax/distributions/normal.py", line 134, in __init__
    with tf.name_scope(name) as name:
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 550, in __enter__
    self._jax_named_scope.__enter__()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: named_scope name argument must be a string.
```

**Comment by sritchie** [comment]
@derifatives this is handled now on `main`!
