### ISSUE TITLE
How to pass a distribution into a generative function as an argument?

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1327]
When running [this file](https://github.com/probcomp/b3d/blob/reproduce/notebooks/bayes3d_paper/reproduce_const_bug.py), we get a strange error.  Here, we are trying to pass a `hyperparams` dictionary into [this generative function](https://github.com/probcomp/b3d/blob/26292af4cd2df168aed7deb160e6087dacac0604/src/b3d/chisight/gen3d/model.py#L15). 
 The hyperparams dictionary contains some GenJAX distributions that get sampled from by the generative function.  We have tried several ways of wrapping the hyperparams dictionary in `Pytree.const`, but this issue has persisted.  Can you please help us understand the right way to do this?

One interesting thing is that this error does not arise the first time we call `importance` on the model; the error arises only once we try calling `importance` again with different GenJAX distributions in the hyperparams dictionary.

Note that the GenJAX distribution objects contain JAX arrays within them (ie. the distribution subclass has internal fields); it is possible this is contributing to the issue.  [Here](https://github.com/probcomp/b3d/blob/26292af4cd2df168aed7deb160e6087dacac0604/src/b3d/chisight/gen3d/transition_kernels.py#L380) is an example definition of one such distribution (and all the other distributions we are trying to pass in in the hyperparams dictionary are defined in the same file).

Our genjax version is 0.5.1.

Here is the error message, from running the first python file I linked to:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<@beartype(genjax._src.core.generative.core.GenerativeFunction.importance) at 0x775a4bdd27a0>", line 76, in importance
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/generative/core.py", line 799, in importance
    tr, w, _, _ = self.update(
                  ^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.update) at 0x775a4998b6a0>", line 77, in update
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 595, in update
    return self.update_change_target(key, trace, subproblem, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.update_change_target) at 0x775a4998b560>", line 102, in update_change_target
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 560, in update_change_target
    ) = update_transform(syntax_sugar_handled)(key, trace, update_problem, argdiffs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.update_transform.wrapper) at 0x77577849e3e0>", line 31, in wrapper
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 377, in wrapper
    retval_diffs = incremental(source_fn)(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.interpreters.incremental.incremental.wrapped) at 0x775778456200>", line 73, in wrapped
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 315, in wrapped
    return interpreter.run_interpreter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 290, in run_interpreter
    _closed_jaxpr, (flat_primals, _, out_tree) = stage(_inner)(*primals)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/staging.py", line 124, in wrapped
    typed_jaxpr = cached_stage_dynamic(flat_fun, tuple(flat_avals))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/staging.py", line 111, in cached_stage_dynamic
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(flat_fun, in_avals)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 288, in _inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/generative/core.py", line 1602, in wrapped
    ret = fn(*args)
          ^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/pytree.py", line 497, in __call__
    return self.fn(*self.dyn_args, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/src/b3d/chisight/gen3d/model.py", line 28, in dynamic_object_generative_model
    visibility_prob_kernel.vmap()(previous_state["visibility_prob"])
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/generative/core.py", line 1658, in __matmul__
    return handle_off_trace_stack(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/generative/core.py", line 1592, in handle_off_trace_stack
    return handler(addr, gen_fn, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.handler_trace_with_static) at 0x775a4998b060>", line 91, in handler_trace_with_static
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 467, in handler_trace_with_static
    return trace(addr if isinstance(addr, tuple) else (addr,), gen_fn, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.trace) at 0x775a49988fe0>", line 89, in trace
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 178, in trace
    return initial_style_bind(trace_p)(_abstract_gen_fn_call)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/forward.py", line 121, in wrapped
    _jaxpr, (flat_args, in_tree, out_tree) = stage(f)(*args, **kwargs)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/staging.py", line 124, in wrapped
    typed_jaxpr = cached_stage_dynamic(flat_fun, tuple(flat_avals))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __eq__
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by femtomc** [comment]
@georgematheos What's happening here is that GenJAX is attempting to create a Jaxpr from your code, so it can then apply a Jaxpr transformation to implement the semantics of `importance` -- every generative function which is traced within the `StaticGenerativeFunction` language has this occur.

Now, obviously -- if we lowered _the same generative function_ multiple times, that's inefficient -- we should cache the Jaxpr, and just return that if we see that generative function again (if we see it again, don't run the lowering process again, just return the Jaxpr so we can apply the transformation)

The error you're seeing is a _cache comparison_ bug -- when you change the arguments, JAX is trying to figure out if it has seen the Pytree type in the arguments before (and then to fetch the cache entry Jaxpr).

The issue is this line in your code: https://github.com/probcomp/b3d/blob/26292af4cd2df168aed7deb160e6087dacac0604/src/b3d/chisight/gen3d/transition_kernels.py#L382C1-L382C49

What `Pytree.static()` means is that _that field is to be treated as a compile time constant -- something which is hashable_,  so you're applying that field annotation wrong. Remove that annotation for fields which may contain JAX arrays.

**Comment by femtomc** [comment]
@sritchie I wonder if we can change `Pytree.static` to prevent usage of any `ArrayLike` type ... that would prevent this footgun -- or insert a static check to see if the value is a JAX array.

**Comment by georgematheos** [comment]
@femtomc thank you!
We do want these arrays that are stored in the distributions to be compile-time constants.  Is there a way to achieve this (e.g. by wrapping some value somewhere in `Pytree.const`)?

**Comment by georgematheos** [comment]
@nishadgothoskar did you try this without `Pytree.static` annotations?  (It sounds like maybe this would work?)

**Comment by nishadgothoskar** [comment]
just tried it and got this error:
```
Traceback (most recent call last):
  File "/home/nishadgothoskar/b3d/notebooks/bayes3d_paper/reproduce_const_bug.py", line 52, in <module>
    trace = importance(key, C.n(), (hyperparams, previous_state))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.generative.core.GenerativeFunction.importance) at 0x7fe0d1fe6e80>", line 77, in importance
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/core/generative/core.py", line 801, in importance
    tr, w, _, _ = self.update(
                  ^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.update) at 0x7fe0c62b6d40>", line 78, in update
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 595, in update
    return self.update_change_target(key, trace, subproblem, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.update_change_target) at 0x7fe0c62b6c00>", line 103, in update_change_target
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 560, in update_change_target
    ) = update_transform(syntax_sugar_handled)(key, trace, update_problem, argdiffs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.update_transform.wrapper) at 0x7fde3c6a53a0>", line 31, in wrapper
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 377, in wrapper
    retval_diffs = incremental(source_fn)(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.interpreters.incremental.incremental.wrapped) at 0x7fde3c6a4c20>", line 73, in wrapped
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 316, in wrapped
    return interpreter.run_interpreter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 296, in run_interpreter
    flat_out = self._eval_jaxpr_forward(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 278, in _eval_jaxpr_forward
    outduals = _stateful_handler.dispatch(_eqn.primitive, *args, **_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 225, in dispatch
    v = self.handle_trace(addr, gen_fn, args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.UpdateHandler.handle_trace) at 0x7fe0c62b5940>", line 89, in handle_trace
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 359, in handle_trace
    (tr, w, retval_diff, bwd_problem) = gen_fn.update(
                                        ^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.combinators.vmap.VmapCombinator.update) at 0x7fe0c62df6a0>", line 78, in update
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/combinators/vmap.py", line 301, in update
    return self.update_change_target(key, trace, subproblem, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.combinators.vmap.VmapCombinator.update_change_target) at 0x7fe0c62df560>", line 103, in update_change_target
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/combinators/vmap.py", line 287, in update_change_target
    return self.update_importance(key, constraint, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/combinators/vmap.py", line 205, in update_importance
    (tr, w, rd, bwd_problem) = jax.vmap(
                               ^^^^^^^^^
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/combinators/vmap.py", line 195, in _importance
    tr, w, rd, bwd_problem = self.gen_fn.update(
                             ^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.update) at 0x7fe0d1e920c0>", line 78, in update
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 467, in update
    return self.update_change_target(key, trace, subproblem, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.update_change_target) at 0x7fe0d1e92020>", line 103, in update_change_target
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 452, in update_change_target
    return self.update_importance(key, constraint, primals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.update_importance) at 0x7fe0d1e919e0>", line 79, in update_importance
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 198, in update_importance
    tr, w, bwd_problem = self.importance_choice_map(key, constraint, args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.importance_choice_map) at 0x7fe0d1e91760>", line 74, in importance_choice_map
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 136, in importance_choice_map
    tr = self.simulate(key, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.simulate) at 0x7fe0d1e914e0>", line 55, in simulate
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 122, in simulate
    (w, v) = self.random_weighted(key, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/b3d/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 522, in random_weighted
    v = self.sample(key, *args)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nishadgothoskar/b3d/src/b3d/chisight/gen3d/transition_kernels.py", line 388, in sample
    * self.possible_values.at[
      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Diff' object has no attribute 'at'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by femtomc** [comment]
Can you explain this line to me;
https://github.com/probcomp/b3d/blob/26292af4cd2df168aed7deb160e6087dacac0604/src/b3d/chisight/gen3d/transition_kernels.py#L388

You’re using the at method and also the get method — presumably you think this is going to work if possible values is a constant — but you’re indexing into it with a JAX value, which won’t be known until runtime.

How will this work?

**Comment by georgematheos** [comment]
@femtomc I think we had been under the impression that `.at[].get()` syntax would do something roughly equivalent to `.dynamic_index()`, but this may be incorrect - we will look into it.

**Comment by georgematheos** [comment]
@nishadgothoskar closing since we have our next steps for sorting this out - we can reopen if we still can't resolve it.

**Comment by georgematheos** [comment]
@femtomc @sritchie
Here is a minimal working example for this issue, on genjax 0.6.1:

```python
import jax
import jax.numpy as jnp
import jax.random as r
import genjax
from genjax import Pytree

@Pytree.dataclass
class MyDistribution(genjax.ExactDensity):
    mean: jnp.ndarray

    def sample(self, key):
        return self.mean + jax.random.normal(key, self.mean.shape)
    
    def logpdf(self, x):
        return -0.5 * jnp.sum((x - self.mean) ** 2)

@genjax.gen
def foo(h):
    dist = h["dist"]
    x = dist() @ "x"
    return x

foo.importance(
    r.PRNGKey(0),
    genjax.ChoiceMapBuilder.n(),
    ({"dist": MyDistribution(jnp.array(11.))},)
)
```

This results in the following error:
```
Traceback (most recent call last):
  File "/home/georgematheos/b3d/mwe.py", line 23, in <module>
    foo.importance(
  File "<@beartype(genjax._src.core.generative.core.GenerativeFunction.importance) at 0x791c313596c0>", line 76, in importance
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/generative/core.py", line 749, in importance
    tr, w, _, _ = self.update(
                  ^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.update) at 0x791c2ef79c60>", line 81, in update
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 588, in update
    return self.update_change_target(key, trace, subproblem, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.StaticGenerativeFunction.update_change_target) at 0x791c2ef79bc0>", line 106, in update_change_target
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 557, in update_change_target
    ) = update_transform(syntax_sugar_handled)(key, trace, update_problem, argdiffs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 368, in wrapper
    retval_diffs = incremental(source_fn)(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 278, in wrapped
    return interpreter.run_interpreter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 260, in run_interpreter
    flat_out = self._eval_jaxpr_forward(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.interpreters.incremental.IncrementalInterpreter._eval_jaxpr_forward) at 0x791c3130ade0>", line 101, in _eval_jaxpr_forward
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/core/interpreters/incremental.py", line 242, in _eval_jaxpr_forward
    outduals = _stateful_handler.dispatch(_eqn.primitive, *args, **_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 220, in dispatch
    v = self.handle_trace(addr, gen_fn, args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.UpdateHandler.handle_trace) at 0x791c2ef787c0>", line 92, in handle_trace
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/static.py", line 351, in handle_trace
    (tr, w, retval_diff, bwd_problem) = gen_fn.update(
                                        ^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.update) at 0x791c3124a3e0>", line 80, in update
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 465, in update
    return self.update_change_target(key, trace, subproblem, argdiffs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.update_change_target) at 0x791c3124a340>", line 105, in update_change_target
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 452, in update_change_target
    return self.update_importance(key, constraint, primals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.update_importance) at 0x791c31249e40>", line 78, in update_importance
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 190, in update_importance
    tr, w, bwd_problem = self.importance_choice_map(key, constraint, args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.importance_choice_map) at 0x791c31249d00>", line 74, in importance_choice_map
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 130, in importance_choice_map
    tr = self.simulate(key, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.Distribution.simulate) at 0x791c31249c60>", line 55, in simulate
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 117, in simulate
    (w, v) = self.random_weighted(key, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.distributions.distribution.ExactDensity.random_weighted) at 0x791c3124bc40>", line 36, in random_weighted
  File "/home/georgematheos/b3d/.pixi/envs/gpu/lib/python3.12/site-packages/genjax/_src/generative_functions/distributions/distribution.py", line 519, in random_weighted
    v = self.sample(key, *args)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/b3d/mwe.py", line 12, in sample
    return self.mean + jax.random.normal(key, self.mean.shape)
                                              ^^^^^^^^^^^^^^^
AttributeError: 'Diff' object has no attribute 'shape'
```

**Comment by georgematheos** [comment]
The simulate method works, however:
```python
foo.simulate(r.PRNGKey(0), (
    {"dist": MyDistribution(jnp.array(11.))},
))
```
returns a trace and does not error.

**Comment by femtomc** [comment]
@georgematheos I'm of two minds about this ... this is a great test case btw!

the problem is that you're hiding a value in the distribution, and then our current (broken) implementation of `importance` lifts everything to `Diff` (because it uses `update` -- this will change in soon to be GenJAX 0.7.0 so you wouldn't get this error in `importance`)

But still, you'd likely run into this error if you tried to use `update`, even in GenJAX 0.7.0 -- and I'm not exactly sure how to prevent this from happening.

In Gen.jl for instance -- say you pass a generative function as an argument to another generative function. How is it possible to know that that generative function _may have closed over `Diff` values_?

Perhaps the answer in `Gen.jl` is that a generative function cannot close over `Diff` values _and also be passed in as an argument to another generative function_ - but in GenJAX, because `GenerativeFunction` is a `Pytree` -- we're unfortunately running into this type of edge case.

**Comment by femtomc** [comment]
Ah -- I see -- I think you actually want to be using the array here as a constant, is that right? And you're trying to find the right idiom for it?

**Comment by georgematheos** [comment]
Yes, that’s right!

**Comment by femtomc** [comment]
@georgematheos Can you try `Pytree.const` with a `numpy` array? (and label your `Distribution` field as static)

**Comment by georgematheos** [comment]
[Wrote this before seeing your last message --]

Previously, we had a lot of code with the structure
```python
def model_factory(hyperparams):
  @genjax.gen
  def foo():
      d = hyperparams["dist"]
      x = d() @ "x"
      return x

  return foo
```

So this is one option for a pattern for this.

In this new draft, we used hyperparams as a generative function arg, and it was somewhat convenient to have the hyperparams packaged up with the trace, so our inference functions could just take the trace, and access hyperparams by looking at its arguments.

**Comment by femtomc** [comment]
@georgematheos There's no reason the thing you wrote shouldn't work (and I believe we should support it, in GenJAX -- we just don't now, and need to think about the right way to handle that sort of "argument is a distribution itself, which may hold arrays")

**Comment by georgematheos** [comment]
Okay, cool!  And thank you - I will try the Pytree const strategy and lyk how it goes.

Makes sense that this is a tricky case -- I don't think this was handled in Gen.jl either.  I don't think it's necessarily critical to support.  If we did want to support it, I guess one question is if it is possible to use `update` to update arguments which contain distributions that are sampled from within a gen fn.  If so, that may complicate the update logic (since the distributions themselves may have changed!)...  An approach that may sidestep this is to say that `update` cannot change these arguments, but we can still generate traces with such arguments through `simulate` and `importance`.

**Comment by littleredcomputer** [comment]
Please see GEN-361 for a thorough discussion of this

**Comment by sritchie** [comment]
In case it doesn't sync from linear, I'll add this here as well...

@georgematheos you might try passing the troublesome argument in via partial_apply on StaticGenerativeFunction, which bundles up the approach that @colin settled on in [GEN-361](https://linear.app/chi-fro/issue/GEN-361/traced-values-leak-in-scan): https://github.com/probcomp/genjax/blob/a84b3691901e54ec276717f42e320f0bfb4bd4f4/src/genjax/_src/generative_functions/static.py#L610

**Comment by sritchie** [comment]
@georgematheos you might try passing the troublesome argument in via `partial_apply` on `StaticGenerativeFunction`, which bundles up the approach that @colin settled on in [GEN-361](https://linear.app/chi-fro/issue/GEN-361/traced-values-leak-in-scan): [https://github.com/probcomp/genjax/blob/a84b3691901e54ec276717f42e320f0bfb4bd4f4/src/genjax/\_src/generative_functions/static.py#L610](https://github.com/probcomp/genjax/blob/a84b3691901e54ec276717f42e320f0bfb4bd4f4/src/genjax/\_src/generative_functions/static.py#L610)

**Comment by georgematheos** [comment]
Great, thank you!
After a bit more discussion with Nishad, I think the right solution for our case may be to just turn the parameter called `mean` in the MWE above into an argument to our generative function, so that our code looks like

```python
@Pytree.dataclass
class MyDistribution(genjax.ExactDensity):
    def sample(self, key, mean):
        return self.mean + jax.random.normal(key, self.mean.shape)
    
    def logpdf(self, x, mean):
        return -0.5 * jnp.sum((x - self.mean) ** 2)

@genjax.gen
def foo(h):
    mean = h["mean"]
    x = dist(mean) @ "x"
    return x

foo.importance(
    r.PRNGKey(0),
    genjax.ChoiceMapBuilder.n(),
    ({"mean": jnp.array(11.)},)
)
```

The reasons I think this is the right move, rather than the approaches above:
- `.partial_apply` can only be used on generative functions, whereas currently our code is written to use `MyDistribution.logpdf` in several places.  (But I suspect that this indicates we aren't using a great genjaxian design pattern.  Should we instead have been using `estimate_logpdf`, and wrapping our gen fns in Marginal calls?  Should we have been using `project` somehow or `get_score`?)
- We want to access the `dist.mean` parameter in our inference code.
- Compared to using a `model_factory`, if we have this `mean` value be an argument, we can change the parameter without having a new generative function which requires waiting for a new pass of JIT compilation to finish.
