### ISSUE TITLE
[BUG] Importing Genjax

### ISSUE THREAD

**Issue by limarta** [genjax-community/genjax#1442]
**Describe the bug**
I made a fresh environment using poetry and couldn't import `genjax` due to this error:
```
>>> import genjax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ian/Documents/probcomp/dpmm_genjax/.venv/lib/python3.12/site-packages/genjax/__init__.py", line 40, in <module>
    from .inference import *
  File "/Users/ian/Documents/probcomp/dpmm_genjax/.venv/lib/python3.12/site-packages/genjax/inference/__init__.py", line 22, in <module>
    from genjax.inference import (
  File "/Users/ian/Documents/probcomp/dpmm_genjax/.venv/lib/python3.12/site-packages/genjax/inference/vi.py", line 15, in <module>
    from genjax._src.inference.vi import (
  File "/Users/ian/Documents/probcomp/dpmm_genjax/.venv/lib/python3.12/site-packages/genjax/_src/inference/vi.py", line 25, in <module>
    from genjax._src.adev.primitives import (
  File "/Users/ian/Documents/probcomp/dpmm_genjax/.venv/lib/python3.12/site-packages/genjax/_src/adev/primitives.py", line 21, in <module>
    from jax.interpreters.ad import instantiate_zeros, recast_to_float0, zeros_like_jaxval
ImportError: cannot import name 'recast_to_float0' from 'jax.interpreters.ad' (/Users/ian/Documents/probcomp/dpmm_genjax/.venv/lib/python3.12/site-packages/jax/interpreters/ad.py)
```

**To Reproduce**
- `poetry init`
- Run steps listed [here](https://genjax.gen.dev/#quickstart) for poetry.

**Expected behavior**
Installation good to go.

**Screenshots**

**Execution environment (please complete the following information):**
 - Tried on M1 and remote instance with CUDA
 - 3.10
 - 0.5 to 0.7

**Additional context**

**Comment by sritchie** [comment]
@ian are you on the latest genjax, on main?

**Comment by sritchie** [comment]
This is definitely not a problem on main… [https://github.com/probcomp/genjax/blob/main/src/genjax/\_src/adev/primitives.py#L21](https://github.com/probcomp/genjax/blob/main/src/genjax/\_src/adev/primitives.py#L21)

**Comment by sritchie** [comment]
@limarta , closing, try again on main and you should be fine.
