### ISSUE TITLE
[BUG] Error with JAX 0.4.36

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1454]
With GenJAX 0.8.0, I get the following error when I upgrade to JAX 0.4.36:
```
(default) georgematheos@pixi-vm-1:~/gen3d$ pixi run python
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genjax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/georgematheos/gen3d/.pixi/envs/default/lib/python3.12/site-packages/genjax/__init__.py", line 40, in <module>
    from .inference import *
  File "/home/georgematheos/gen3d/.pixi/envs/default/lib/python3.12/site-packages/genjax/inference/__init__.py", line 22, in <module>
    from genjax.inference import (
  File "/home/georgematheos/gen3d/.pixi/envs/default/lib/python3.12/site-packages/genjax/inference/vi.py", line 15, in <module>
    from genjax._src.inference.vi import (
  File "/home/georgematheos/gen3d/.pixi/envs/default/lib/python3.12/site-packages/genjax/_src/inference/vi.py", line 25, in <module>
    from genjax._src.adev.primitives import (
  File "/home/georgematheos/gen3d/.pixi/envs/default/lib/python3.12/site-packages/genjax/_src/adev/primitives.py", line 21, in <module>
    from jax.interpreters.ad import instantiate_zeros, zeros_like_jaxval
ImportError: cannot import name 'zeros_like_jaxval' from 'jax.interpreters.ad' (/home/georgematheos/gen3d/.pixi/envs/default/lib/python3.12/site-packages/jax/interpreters/ad.py). Did you mean: 'zeros_like_aval'?
```

My JAX version is:
```
>>> jax.__version__
'0.4.36'
>>> jax.lib.__version__
'0.4.36'
```

**Comment by sritchie** [comment]
Try downgrading JAX, looks like another jax compatibility bug!
