### ISSUE TITLE
Build fails on M1 Mac Mini with python and poetry installed via homebrew

### ISSUE THREAD

**Issue by cameronfreer** [genjax-community/genjax#2]
Output of running `poetry install` within a fresh clone of the repo (commit 52ad4e1):

```
➜  genjax git:(main) poetry install
Creating virtualenv genjax-l_6UMbRS-py3.10 in /Users/freer/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 47 installs, 0 updates, 0 removals

  • Installing pyparsing (3.0.9)
  • Installing attrs (22.1.0)
  • Installing distlib (0.3.5)
  • Installing filelock (3.8.0)
  • Installing importlib-resources (5.9.0)
  • Installing iniconfig (1.1.1)
  • Installing markupsafe (2.1.1)
  • Installing mccabe (0.7.0)
  • Installing numpy (1.23.2)
  • Installing packaging (21.3)
  • Installing platformdirs (2.5.2)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing pycodestyle (2.9.1)
  • Installing pyflakes (2.5.0)
  • Installing tomli (2.0.1)
  • Installing typing-extensions (4.3.0)
  • Installing zipp (3.8.1)
  • Installing absl-py (1.2.0)
  • Installing cfgv (3.3.1)
  • Installing click (8.1.3)
  • Installing etils (0.7.1)
  • Installing flake8 (5.0.4)
  • Installing identify (2.5.3)
  • Installing jinja2 (3.1.2)
  • Installing mypy-extensions (0.4.3)
  • Installing nodeenv (1.7.0)
  • Installing opt-einsum (3.3.0)
  • Installing pathspec (0.9.0)
  • Installing py-cpuinfo (8.0.0)
  • Installing pygments (2.13.0)
  • Installing pyyaml (6.0)
  • Installing pytest (7.1.2)
  • Installing scipy (1.9.0): Failed

  EnvCommandError

  Command ['/Users/freer/Library/Caches/pypoetry/virtualenvs/genjax-l_6UMbRS-py3.10/bin/pip', 'install', '--no-deps', 'file:///Users/freer/Library/Caches/pypoetry/artifacts/8f/36/df/d9145a2fada85fc128f183d700f53795b08f590278f49dfb4d0051fd2b/scipy-1.9.0.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/freer/Library/Caches/pypoetry/artifacts/8f/36/df/d9145a2fada85fc128f183d700f53795b08f590278f49dfb4d0051fd2b/scipy-1.9.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [60 lines of output]
        The Meson build system
        Version: 0.62.2
        Source dir: /private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74
        Build dir: /private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74/.mesonpy-kynr5cnq/build
        Build type: native build
        Project name: SciPy
        Project version: 1.9.0
        C compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
        C linker for the host machine: cc ld64 711
        C++ compiler for the host machine: c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
        C++ linker for the host machine: c++ ld64 711
        Host machine cpu family: aarch64
        Host machine cpu: arm64
        Compiler for C supports arguments -Wno-unused-but-set-variable: NO
        Library m found: YES
        Fortran compiler for the host machine: gfortran (gcc 12.1.0 "GNU Fortran (Homebrew GCC 12.1.0) 12.1.0")
        Fortran linker for the host machine: gfortran ld64 711
        Program cython found: YES (/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/bin/cython)
        Program pythran found: YES (/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/bin/pythran)
        Program cp found: YES (/bin/cp)
        Program python3 found: YES (/Users/freer/Library/Caches/pypoetry/virtualenvs/genjax-l_6UMbRS-py3.10/bin/python)
        Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
        Library npymath found: YES
        Library npyrandom found: YES
        Did not find CMake 'cmake'
        Found CMake: NO
        Run-time dependency openblas found: NO (tried pkgconfig and framework)

        ../../scipy/meson.build:120:0: ERROR: Dependency "openblas" not found, tried pkgconfig and framework

        A full log can be found at /private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74/.mesonpy-kynr5cnq/build/meson-logs/meson-log.txt
        + meson setup --native-file=/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10 /private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74 /private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74/.mesonpy-kynr5cnq/build
        Traceback (most recent call last):
          File "/Users/freer/Library/Caches/pypoetry/virtualenvs/genjax-l_6UMbRS-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/Users/freer/Library/Caches/pypoetry/virtualenvs/genjax-l_6UMbRS-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/freer/Library/Caches/pypoetry/virtualenvs/genjax-l_6UMbRS-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 909, in get_requires_for_build_wheel
            with _project(config_settings) as project:
          File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
            return next(self.gen)
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 888, in _project
            with Project.with_temp_working_dir(
          File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
            return next(self.gen)
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 547, in with_temp_working_dir
            yield cls(source_dir, tmpdir, build_dir)
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 463, in __init__
            self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 494, in _configure
            self._meson(
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 477, in _meson
            return self._proc('meson', *args)
          File "/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-build-env-fdde_9yj/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 472, in _proc
            subprocess.check_call(list(args))
          File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10', '/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74', '/private/var/folders/v_/wvm9czn12x17rk45cv4yy6cc0000gn/T/pip-req-build-qi8u3y74/.mesonpy-kynr5cnq/build']' returned non-zero exit status 1.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.

  [notice] A new release of pip available: 22.1.2 -> 22.2.2
  [notice] To update, run: pip install --upgrade pip


  at /opt/homebrew/Cellar/poetry/1.1.14/libexec/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

  • Installing toml (0.10.2)
  • Installing virtualenv (20.16.3)
```

**Comment by femtomc** [comment]
@alex-lew if you’ve tried to build — did you run into any issues on your MacBook?

**Comment by alex-lew** [comment]
I didn't run into any issues, but I do have CMake installed, and it's possible I also have installed OpenBLAS separately (e.g. if it was needed to run Nishad's InverseGraphics code?)

**Comment by femtomc** [comment]
@cameronfreer do you still want this open?

**Comment by cameronfreer** [comment]
I still don't have any way of running GenJax on that machine, but it's okay
with me if you prefer to close it.

**Comment by femtomc** [comment]
@cameronfreer I'm basically going to write this off as a `scipy` issue -- given the fact that we know building `scipy` can sometimes be problematic...
