### ISSUE TITLE
[BUG]: can't install Genjax on MBP M2

### ISSUE THREAD

**Issue by MathieuHuot** [genjax-community/genjax#445]
`>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/genjax-py311/lib/python3.11/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/usr/local/anaconda3/envs/genjax-py311/lib/python3.11/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/genjax-py311/lib/python3.11/site-packages/jax/_src/config.py", line 24, in <module>
    from jax._src import lib
  File "/usr/local/anaconda3/envs/genjax-py311/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 84, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
`

**Comment by femtomc** [comment]
In your terminal, use the ‘arch’ command and report back to me what it says

**Comment by sritchie** [comment]
@MathieuHuot , closing this in prep for our new release — I can get jax working in CPU mode on an M1 so I think this is worked out.
