### ISSUE TITLE
[BUG] MapTrace keeps repeated copies of args around that are not mapped over.

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#461]
I am getting an out of memory error when I run my sensor model. It seems like this is caused by the trace containing the arguments of a mapped sub model:
```
X = genjax.Map(_sensor_model_ij, (0,0,None,None))(I,J,Y_,sig) @ "X"
```
Here's a trace for smaller array shape so I don't get the error (full trace in the figure)
```
MapTrace
└── ...

        args
        └── tuple
        ├──  i32[200]
        ├──  i32[200]
        ├──  f32[200,10,20,3]
        └──  f32[200]
```
The problem seems to be the third arg of shape `f32[200,10,20,3]`. The `200` comes from the length of `I` and `J` which are mapped over, and `[10,20,3]` comes from `Y_`.

Why is it keeping all of it arround??

**Comment by mirkoklukas** [comment]
Trying to close over the args we dont want to be repeated, throws a leak error. 
Seems to be caused by the following pattern that i tried:

```python
def make_submodel(x):

    @gen
    def submodel():
        y = genjax.normal(x,1.0) @ "y"
        return y
    
    return submodel


@gen
def model(x):    

    f = make_submodel(x)
    y = f() @ "y"

    return y


key = keysplit(key)
tr = model.simulate(key, (1.0,))
```

![image](https://github.com/probcomp/genjax/assets/5437585/73be8f99-d148-4487-9341-10ca208ceb1c)

**Comment by femtomc** [comment]
@mirkoklukas there’s some functionality I’m testing out on the `nightly` branch to avoid this issue.

It’s called `DropArgumentsGenerativeFunction` — you can see usage here:

https://github.com/probcomp/genjax/blob/nightly/tests/generative_functions/test_drop_arguments.py

**Comment by sritchie** [comment]
@femtomc is this still a problem?

**Comment by sritchie** [comment]
Confirming that this is still an issue on nightly:

```python
import genjax
import jax

def make_submodel(x):
 
    @genjax.gen
    def submodel():
        y = genjax.normal(x,1.0) @ "y"
        return y
     
    return submodel
 
 
@genjax.gen
def model(x):
    f = make_submodel(x)
    y = f() @ "y"
    return y
 
key = jax.random.PRNGKey(314159)
tr = model.simulate(key, (1.0,))
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/equinox/_module.py", line 1053, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.static_gen_fn.StaticGenerativeFunction.simulate) at 0x2c06e1e40>", line 55, in simulate
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_gen_fn.py", line 129, in simulate
    (args, retval, address_choices, score), cache_state = simulate_transform(
                                                          ^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_transforms.py", line 286, in wrapper
    retval = forward(source_fn)(stateful_handler, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.interpreters.forward.forward.wrapped) at 0x2c1141080>", line 32, in wrapped
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 251, in wrapped
    return interpreter.run_interpreter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/equinox/_module.py", line 1053, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 236, in run_interpreter
    flat_out = self._eval_jaxpr_forward(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/equinox/_module.py", line 1053, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 221, in _eval_jaxpr_forward
    outvals = stateful_handler.dispatch(eqn.primitive, *args, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_transforms.py", line 235, in dispatch
    return self.handle_trace(*tracers, **_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_transforms.py", line 271, in handle_trace
    tr = gen_fn.simulate(sub_key, call_args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/equinox/_module.py", line 1053, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.static_gen_fn.StaticGenerativeFunction.simulate) at 0x2c06e1e40>", line 55, in simulate
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_gen_fn.py", line 129, in simulate
    (args, retval, address_choices, score), cache_state = simulate_transform(
                                                          ^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_transforms.py", line 286, in wrapper
    retval = forward(source_fn)(stateful_handler, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.core.interpreters.forward.forward.wrapped) at 0x2c11225c0>", line 32, in wrapped
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 251, in wrapped
    return interpreter.run_interpreter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/equinox/_module.py", line 1053, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 234, in run_interpreter
    _closed_jaxpr, (flat_args, _, out_tree) = stage(_inner)(*args)
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/staging.py", line 81, in wrapped
    typed_jaxpr = cached_stage_dynamic(flat_fun, tuple(flat_avals))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/linear_util.py", line 350, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/staging.py", line 68, in cached_stage_dynamic
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(flat_fun, in_avals)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/interpreters/partial_eval.py", line 103, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, () = _trace_to_jaxpr_dynamic(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/profiler.py", line 335, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2322, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2344, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/linear_util.py", line 192, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 232, in _inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/supports_callees.py", line 46, in wrapped
    ret = fn(*args)
          ^^^^^^^^^
  File "<stdin>", line 5, in submodel
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/supports_callees.py", line 28, in __matmul__
    return handle_off_trace_stack(addr, self.gen_fn, self.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/supports_callees.py", line 40, in handle_off_trace_stack
    return handler(addr, gen_fn, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(genjax._src.generative_functions.static.static_gen_fn.handler_trace_with_static) at 0x2c0658a40>", line 51, in handler_trace_with_static
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_gen_fn.py", line 61, in handler_trace_with_static
    return trace(addr, gen_fn)(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_transforms.py", line 142, in <lambda>
    return lambda *args: _trace(gen_fn, addr, *args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/generative_functions/static/static_transforms.py", line 122, in _trace
    return initial_style_bind(trace_p)(_abstract_gen_fn_call)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py", line 119, in wrapped
    outs = prim.bind(
           ^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/core.py", line 422, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/core.py", line 1337, in find_top_trace
    top_tracer._assert_live()
  File "/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 1720, in _assert_live
    raise core.escaped_tracer_error(self, None)
jax.errors.UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX had a side effect, allowing for a reference to an intermediate value with type float32[] wrapped in a DynamicJaxprTracer to escape the scope of the transformation.
JAX transformations require that functions explicitly return their outputs, and disallow saving intermediate values to global state.
------------------------------
The leaked intermediate value was created on line /Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/staging.py:68:23 (cached_stage_dynamic).
------------------------------
When the value was created, the final 5 stack frames (most recent last) excluding JAX-internal frames were:
------------------------------
/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py:251:15 (forward.<locals>.wrapped)
/Users/sritchie/code/python/genjax/.venv/lib/python3.11/site-packages/equinox/_module.py:1053:15 (BoundMethod.__call__)
/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/forward.py:234:50 (ForwardInterpreter.run_interpreter)
/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/staging.py:81:22 (stage.<locals>.wrapped)
/Users/sritchie/code/python/genjax/src/genjax/_src/core/interpreters/staging.py:68:23 (cached_stage_dynamic)
------------------------------

To catch the leak earlier, try setting the environment variable JAX_CHECK_TRACER_LEAKS or using the `jax.checking_leaks` context manager.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.UnexpectedTracerError
```

**Comment by sritchie** [comment]
@mirkoklukas the solution is to use the new `partial_apply` on `StaticGenerativeFunction`:

```python
import genjax
import jax

def make_submodel(x):
 
    @genjax.gen
    def submodel():
        y = genjax.normal(x,1.0) @ "y"
        return y
     
    return submodel
 
 
@genjax.gen
def model(x):
    f = make_submodel(x)
    y = f() @ "y"
    return y
 
key = jax.random.PRNGKey(314159)

# See the change here
tr = model.partial_apply(1.0).simulate(key, ())
```

This is equivalent to doing

```python
tr = genjax.gen(genjax.Pytree.partial(1.0)(model.inline)).simulate(key, ())
```
